# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required version
version: 2

# Specify the build environment
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

# Python dependencies for building the docs
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-docs.txt
